/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Textbook Overview',
    },
    {
      type: 'category',
      label: 'Module 1: Humanoid Robotics',
      items: [
        {
          type: 'doc',
          id: 'chapter1',
          label: 'Humanoid Robotics Fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: ROS 2',
      items: [
        {
          type: 'doc',
          id: 'chapter2',
          label: 'ROS 2 - Robotic Nervous System',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Digital Twins',
      items: [
        {
          type: 'doc',
          id: 'chapter3',
          label: 'Digital Twins - Gazebo & Unity',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: AI-Robot Brain',
      items: [
        {
          type: 'doc',
          id: 'chapter4',
          label: 'AI-Robot Brain - NVIDIA Isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Vision-Language-Action Systems',
      items: [
        {
          type: 'doc',
          id: 'chapter5',
          label: 'Vision-Language-Action Systems',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 6: Hardware Laboratory',
      items: [
        {
          type: 'doc',
          id: 'chapter6',
          label: 'Hardware Laboratory',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 7: Capstone Project',
      items: [
        {
          type: 'doc',
          id: 'chapter7',
          label: 'Capstone Project',
        },
      ],
    },
  ],
};

module.exports = sidebars;